<?php

/**
 * @file
 * Primary module hooks for Lehigh IIIP module.
 */

use Drupal\islandora_collection_tabs\Plugin\Field\FieldType\CollectionTabsItem;
use Drupal\node\NodeForm;
use Drupal\views\ViewExecutable;

/**
 * Implements hook_views_pre_render().
 */
function lehigh_iiip_views_pre_render(ViewExecutable $view) {
  if ($view->id() !== 'collection_tabs') {
    return;
  }
  foreach ($view->result as $row) {
    $entity = $row->_entity ?? NULL;
    if (!$entity || !$entity->hasField('field_collection_tabs') || !isset($view->field['field_collection_tabs'])) {
      continue;
    }

    $field_item = $entity->get('field_collection_tabs')->first();
    if ($field_item && $field_item->display === CollectionTabsItem::DISPLAY_IIIP) {
      $field_handler = $view->field['field_collection_tabs'];
      $field_handler->options['type'] = 'lehigh_iiip_collection_formatter';
      break;
    }
  }
}

/**
 * Implements hook_entity_type_alter().
 */
function lehigh_iiip_entity_type_alter(array &$entity_types) {
  if (isset($entity_types['node'])) {
    $entity_types['node']->setFormClass('iiip_submission', NodeForm::class);
  }
}
