http:
  services:
    fabricator:
      loadBalancer:
        servers:
          - url: http://fabricator:8080
    fabricator-proxy-service:
      loadBalancer:
        servers:
          - url: https://islandora-stage.lib.lehigh.edu/workbench

  middlewares:
    fabricator-proxy-headers:
      headers:
        customRequestHeaders:
          Host: islandora-stage.lib.lehigh.edu

  routers:
    # send prod requests for fabricator to staging
    fabricator-proxy:
      rule: Host(`preserve.lehigh.edu`) && PathPrefix(`/workbench`)
      tls: {}
      middlewares:
        - fabricator-proxy-headers
      service: fabricator-proxy-service
      priority: 100
    fabricator:
      rule: PathPrefix(`/workbench`)
      tls: {}
      service: fabricator
