<?php

/**
 * @file
 * Contains lehigh_embargo.module.
 */

use Drupal\Core\Datetime\DrupalDateTime;

define('LEHIGH_EMBARGO_INDEFINITE', '2999-12-31');

/**
 * Implements hook_preprocess_media().
 */
function lehigh_embargo_preprocess_media(&$vars) {
  if ($vars['view_mode'] !== 'default_islandora_display') {
    return;
  }
  $media = $vars['media'];
  $node = $media->get('field_media_of')->entity;

  $embargoDate = lehigh_embargo_node_is_embargoed($node);
  if (!$embargoDate) {
    return;
  }

  $date = $embargoDate->format('Y-m-d');
  $embargo_suffix = 'until ' . $date;
  if ($date == LEHIGH_EMBARGO_INDEFINITE) {
    $embargo_suffix = 'indefinitely';
  }

  $vars['content'] = [
    '#markup' => '<div class="alert alert-warning" role="alert">
      This file is embargoed '
    . $embargo_suffix
    . '</div>',
  ];
}

/**
 * Implements hook_preprocess_block().
 */
function lehigh_embargo_preprocess_block(&$vars) {
  if (!empty($vars['plugin_id']) && $vars['plugin_id'] == 'views_block:downloads-block_1') {
    $route_match = \Drupal::routeMatch();
    $node = $route_match->getParameter('node');
    if (lehigh_embargo_node_is_embargoed($node)) {
      $vars['content'] = [];
      $vars['label'] = '';
      return;
    }
  }
}

/**
 * Implements hook_metatags_attachments_alter().
 */
function lehigh_embargo_metatags_attachments_alter(array &$metatag_attachments) {
  $node = \Drupal::routeMatch()->getParameter('node');
  if (!$node || !is_object($node) || $node->bundle() !== 'islandora_object') {
    return;
  }

  if (!lehigh_embargo_node_is_embargoed($node)) {
    return;
  }

  foreach ($metatag_attachments['#attached']['html_head'] as $id => $attachment) {
    if ($attachment[1] == 'citation_pdf_url') {
      unset($metatag_attachments['#attached']['html_head'][$id]);
    }
  }
}

/**
 * Check if a node is embargoed.
 */
function lehigh_embargo_node_is_embargoed($node) {
  if (!is_object($node) ||
    !$node->hasField('field_edtf_date_embargo') ||
    $node->field_edtf_date_embargo->isEmpty()) {
    return FALSE;
  }

  foreach ($node->field_edtf_date_embargo as $embargo) {
    $dt = new DrupalDateTime($embargo->value, 'UTC');
    if ($dt->getTimestamp() > time()) {
      return $dt;
    }
  }

  return FALSE;
}
