services:
  alpaca:
    environment:
      ALPACA_MAX_REDELIVERIES: 1
      ALPACA_DERIVATIVE_HOUDINI_CONSUMERS: 3
      ALPACA_DERIVATIVE_HOUDINI_URL: http://houdini:8080
      ALPACA_DERIVATIVE_LIBREOFFICE_URL: http://libreoffice:8080
  coverpage:
    image: ghcr.io/lehigh-university-libraries/scyllaridae-coverpage:main@sha256:1717fcd66dc640bba059386764f8c67151a5861438f6ce68041d900f5088cd71
    environment:
      JWKS_URI: https://${DOMAIN}/oauth/discovery/keys
    volumes:
      - ./certs/rootCA.pem:/app/ca.pem:r
  mergepdf:
    image: islandora/mergepdf:6.3.3@sha256:b338684982d46c2a00215f7b70fd7a37cae5619da097fddc72d251ebb125716f
    environment:
      JWKS_URI: https://${DOMAIN}/oauth/discovery/keys
      MAX_THREADS: 3
    volumes:
      - ./certs/rootCA.pem:/app/ca.pem:r
  libreoffice:
    image: ghcr.io/lehigh-university-libraries/scyllaridae-libreoffice:main@sha256:2fdd97905302e66f70d4f5d2804529e548493590b0905b1dd962f2ca8cbcd56d
    environment:
      JWKS_URI: https://${DOMAIN}/oauth/discovery/keys
    volumes:
      - ./certs/rootCA.pem:/app/ca.pem:r
  houdini:
    image: islandora/houdini:6.3.3@sha256:b42fffae44fe1ef5d2f0c1f6344573ff111c3490d57a8dca8423db16ef348f18
    environment:
      JWKS_URI: https://${DOMAIN}/oauth/discovery/keys
    volumes:
      - ./tmp/houdini:/tmp:rw
      - ./certs/rootCA.pem:/app/ca.pem:r
  parry:
    volumes:
      - ./conf/parry/scyllaridae.ci.yml:/app/scyllaridae.yml:r
  mariadb:
    image: mariadb:11.8.5-noble@sha256:345fa26d595e8c7fe298e0c4098ed400356f502458769c8902229b3437d6da2b
    secrets:
      - source: DB_ROOT_PASSWORD
        target: MARIADB_ROOT_PASSWORD
    healthcheck:
      test: test /run/mysqld/mysqld.sock
  github-actions-runner:
    image: ghcr.io/lehigh-university-libraries/actions-runner:main
    environment:
      GITHUB_RUNNER_TOKEN: ${GITHUB_RUNNER_TOKEN}
      GITHUB_REPO: "https://github.com/lehigh-university-libraries/isle-preserve"
      LABELS: isle
      KUBECONFIG: /etc/kubeconfigs/ci.yaml
    volumes:
      - actions-runner-data:/app:rw
      - /var/run/docker.sock:/var/run/docker.sock:z
      - ./conf/kubeconfigs:/etc/kubeconfigs:r
  gha-runner-updater:
    image: ghcr.io/lehigh-university-libraries/actions-runner:main
    working_dir: /app
    entrypoint: /bin/sh
    command: -c "while true; do /app/scripts/ci/update-gha.sh; sleep 600; done"
    environment:
      KUBECONFIG: /etc/kubeconfigs/ci.yaml
      KUBE_SVC_ACCOUNT: isle-ci
      KUBE_NAMESPACE: islandora-metadata
      KUBE_CA_CERT_FILE: /run/secrets/KUBE_CA_CERT
      KUBE_SERVER_URL: ${KUBE_SERVER_URL}
    secrets:
      - KUBE_CA_CERT
    volumes:
      - ./:/app
      - /home/rollout/.docker:/root/.docker
      - /home/rollout/.env:/home/rollout/.env
      - /var/run/docker.sock:/var/run/docker.sock:z
      - ./conf/kubeconfigs:/etc/kubeconfigs:rw
secrets:
  KUBE_CA_CERT:
    file: ./certs/kube.base64.pem
