services:
  alpaca:
    environment:
      ALPACA_DERIVATIVE_FITS_URL: http://crayfits:8080
      ALPACA_DERIVATIVE_OCR_URL: http://hypercube:8080
      ALPACA_DERIVATIVE_HOMARUS_URL: http://homarus:8080
      ALPACA_DERIVATIVE_HOUDINI_URL: http://houdini:8080
      ALPACA_DERIVATIVE_LIBREOFFICE_URL: http://libreoffice:8080
      ALPACA_DERIVATIVE_WHISPER_URL: http://whisper:8080
      ALPACA_DERIVATIVE_OCRPDF_URL: http://ocrpdf:8080
      ALPACA_DERIVATIVE_HTR_URL: http://ocrpdf:8080
  drupal-cron:
    profiles: [none]
  rollout:
    profiles: [none]
  drupal-lehigh:
    profiles: [none]
  traefik:
    ports:
      - 8080:8080
  drupal:
    build:
      context: ./drupal
      x-bake:
        cache-from:
          - type=registry,ref=ghcr.io/lehigh-university-libraries/${COMPOSE_PROJECT_NAME}:local
          - type=registry,ref=ghcr.io/lehigh-university-libraries/${COMPOSE_PROJECT_NAME}:main
        cache-to:
          - type=inline
        platforms:
          - linux/arm64
    environment:
      URI_SCHEME: http
      DRUPAL_ENABLE_HTTPS: "false"
    secrets:
      - source: UID
    volumes:
      - drupal-public-files:/var/www/drupal/web/sites/default/files:rw
      - ./tmp/drupal-private-files:/var/www/drupal/private:rw
      - fcrepo-data:/fcrepo:rw
      - ./tmp/drupal:/tmp:rw
      - ./tmp/nginx:/var/lib/nginx/tmp:rw
      - ./tmp/nginx-cache:/var/cache/nginx:rw
      - ./drupal/rootfs/var/www/drupal:/var/www/drupal:z,rw,${CONSISTENCY}
  mariadb:
    ports:
      - 3306:3306
  memcached:
    command: memcached -m 256 -I 5m
  fits:
    image: islandora/fits:alpine-3-24@sha256:caa59516f364d4c136526d1be8566e37cbce3fd9928f7454d82ed25843410fbf
    volumes:
      - ./tmp/fits:/tmp:rw
  crayfits:
    image: islandora/crayfits:alpine-3-24@sha256:b0de536dd16f4a1dfe9541224c1e8e4ef7e321f14cd9c365a591cbe809073c1f
    environment:
      JWKS_URI: https://${DOMAIN}/oauth/discovery/keys
    volumes:
      - ./tmp/crayfits:/tmp:rw
      - ./certs/rootCA.pem:/app/ca.pem:r
  hls:
    image: ghcr.io/lehigh-university-libraries/scyllaridae-hls:main@sha256:99e944891f513ea6379466efce2f0474e8f7f55701e5740b1d6cb700bf541283
    environment:
      JWKS_URI: https://${DOMAIN}/oauth/discovery/keys
    secrets:
      - source: CERT_PUBLIC_KEY
      - source: CERT_AUTHORITY
      - source: JWT_PUBLIC_KEY
  homarus:
    image: islandora/homarus:alpine-3-24@sha256:1f2b990f1f9b109155792c8af01bba54d5500e37e294a21a044ef219452a8a1b
    environment:
      JWKS_URI: https://${DOMAIN}/oauth/discovery/keys
    volumes:
      - ./tmp/homarus:/tmp:rw
      - ./certs/rootCA.pem:/app/ca.pem:r
  houdini:
    image: islandora/houdini:alpine-3-24@sha256:673f62abc452e34ea777a9d4ebecbd4be16615f2b8eccd8c2ce159b7aebbbfca
    environment:
      JWKS_URI: https://${DOMAIN}/oauth/discovery/keys
    volumes:
      - ./tmp/houdini:/tmp:rw
      - ./certs/rootCA.pem:/app/ca.pem:r
  hypercube:
    image: islandora/hypercube:alpine-3-24@sha256:dcaa66816034ed634751f75d12a197c2ec1cef153aa0fca493b5ee57f3ce3891
    environment:
      JWKS_URI: https://${DOMAIN}/oauth/discovery/keys
    volumes:
      - ./tmp/hypercube:/tmp:rw
      - ./certs/rootCA.pem:/app/ca.pem:r
  ocrpdf:
    image: ghcr.io/lehigh-university-libraries/scyllaridae-ocrpdf:main@sha256:74f310b6657219ceafe86b689a28bdf32d9090dd6ca4bae995177d05860e3d16
    environment:
      JWKS_URI: https://${DOMAIN}/oauth/discovery/keys
  libreoffice:
    image: ghcr.io/lehigh-university-libraries/scyllaridae-libreoffice:main@sha256:52181ee0a4241d75ce31510e267c874d651a83b5574191cb619ecc4230e3e7dd
    environment:
      JWKS_URI: https://${DOMAIN}/oauth/discovery/keys
    secrets:
      - source: CERT_PUBLIC_KEY
      - source: CERT_AUTHORITY
      - source: JWT_PUBLIC_KEY
  coverpage:
    image: ghcr.io/lehigh-university-libraries/scyllaridae-coverpage:main@sha256:2530ccfafa9f6abcc78a7bc77edfc094a89a67798fca1779f3c314fa2e107f36
    environment:
      JWKS_URI: https://${DOMAIN}/oauth/discovery/keys
    secrets:
      - source: CERT_PUBLIC_KEY
      - source: CERT_AUTHORITY
      - source: JWT_PUBLIC_KEY
  mergepdf:
    image: islandora/mergepdf:alpine-3-24@sha256:dbba2f6614c48cff59074139ad7acfea9284961166917d6eeae41f96329c8a98
    environment:
      JWKS_URI: https://${DOMAIN}/oauth/discovery/keys
      MAX_THREADS: 3
    secrets:
      - source: CERT_PUBLIC_KEY
      - source: CERT_AUTHORITY
      - source: JWT_PUBLIC_KEY
  drupal-static:
    volumes:
      - ./tmp/drupal-private-files/canonical/${DOMAIN}/0:/usr/share/nginx/drupal:ro
      - ./tmp/drupal-private-files/iiif/${DOMAIN}/294de3557d9d00b3d2d8a1e6aab028cf:/usr/share/nginx/iiif:ro
      - drupal-public-files:/var/www/drupal/web/sites/default/files:ro
      - ./tmp/drupal-static:/tmp:rw
      - ./tmp/nginx-static:/var/lib/nginx/tmp:rw
      - ./tmp/nginx-static-cache:/var/cache/nginx:rw
      - ./tmp/drupal/web:/var/www/drupal/web:rw
  fcrepo:
    volumes:
      - fcrepo-data:/data:rw
      - ./tmp/fcrepo:/tmp:rw
  triplet:
    volumes:
      - drupal-public-files:/public:r
      - ./tmp/drupal-private-files:/private:r
      - fcrepo-data:/fcrepo:r
      - ./certs/rootCA.pem:/etc/ssl/certs/lehigh.pem:r
      - ./conf/triplet/config.yaml:/etc/triplet/config.yaml:r
      - ./tmp/triplet-cache:/var/lib/triplet/cache:rw
