services:
  drupal:
    volumes:
      - ./drupal/rootfs/var/www/drupal/config:/var/www/drupal/config:z,rw,${CONSISTENCY}
  fabricator:
    volumes:
      - /mnt/islandora_staging:/data:r
      - /home/runner/etds:/home/runner/etds:r
  mariadb:
    image: mariadb:11.7.2-noble@sha256:fcc7fcd7114adb5d41f14d116b8aac45f94280d2babfbbb71b4782922ee6d8d4
    secrets:
      - source: DB_ROOT_PASSWORD
        target: MARIADB_ROOT_PASSWORD
    healthcheck:
      test: test /run/mysqld/mysqld.sock
  github-actions-runner:
    image: ghcr.io/lehigh-university-libraries/docker-builds/actions-runner:main
    environment:
      GITHUB_RUNNER_TOKEN: ${GITHUB_RUNNER_TOKEN}
      GITHUB_REPO: "https://github.com/lehigh-university-libraries/fabricator"
      LABELS: workbench
    volumes:
      - actions-runner-data:/app:rw
      - /mnt/islandora_staging:/mnt/islandora_staging:ro
      - /home/runner:/home/runner:rw

