services:
  alpaca:
    environment:
      ALPACA_MAX_REDELIVERIES: 1
      ALPACA_DERIVATIVE_HOUDINI_CONSUMERS: 3
      ALPACA_DERIVATIVE_HOUDINI_URL: http://houdini:8080
      ALPACA_DERIVATIVE_LIBREOFFICE_URL: http://libreoffice:8080
      ALPACA_DERIVATIVE_MERGEPDF_URL: http://mergepdf:8080
      ALPACA_DERIVATIVE_COVERPAGE_URL: http://coverpage:8080
  coverpage:
    image: ghcr.io/lehigh-university-libraries/scyllaridae-coverpage:main@sha256:006841e1c671391203ba9bd26541b7baf3f88cf390d3d853ee5dca360717f29f
    environment:
      JWKS_URI: https://${DOMAIN}/oauth/discovery/keys
    volumes:
      - ./certs/rootCA.pem:/app/ca.pem:r
  mergepdf:
    image: islandora/mergepdf:6.4.3@sha256:fcd7c2e81a67df773d5acbcbf6d307e1552f46722591ddeaf8f949b42ae2c97d
    environment:
      JWKS_URI: https://${DOMAIN}/oauth/discovery/keys
      MAX_THREADS: 3
    secrets:
      - source: CERT_PUBLIC_KEY
      - source: CERT_AUTHORITY
      - source: JWT_PUBLIC_KEY
  libreoffice:
    image: ghcr.io/lehigh-university-libraries/scyllaridae-libreoffice:main@sha256:7855fd5f613e6c57dc0d1f1eafc2674e6c6811f31a600b8c7ec3c459a5faae38
    environment:
      JWKS_URI: https://${DOMAIN}/oauth/discovery/keys
    secrets:
      - source: CERT_PUBLIC_KEY
      - source: CERT_AUTHORITY
      - source: JWT_PUBLIC_KEY
  houdini:
    image: islandora/houdini:6.4.3@sha256:34406f7703e02ed164a9029afd884d1586f24b71b3a50a01a1e422cebf82085f
    environment:
      JWKS_URI: https://${DOMAIN}/oauth/discovery/keys
    secrets:
      - source: CERT_PUBLIC_KEY
      - source: CERT_AUTHORITY
      - source: JWT_PUBLIC_KEY
    volumes:
      - ./tmp/houdini:/tmp:rw
  github-actions-runner:
    image: ghcr.io/lehigh-university-libraries/actions-runner:main
    environment:
      GITHUB_RUNNER_TOKEN: ${GITHUB_RUNNER_TOKEN}
      GITHUB_REPO: "https://github.com/lehigh-university-libraries/isle-preserve"
      LABELS: isle
      KUBECONFIG: /etc/kubeconfigs/ci.yaml
    volumes:
      - actions-runner-data:/app:rw
      - /var/run/docker.sock:/var/run/docker.sock:z
      - ./conf/kubeconfigs:/etc/kubeconfigs:r
  gha-runner-updater:
    image: ghcr.io/lehigh-university-libraries/actions-runner:main
    working_dir: /app
    entrypoint: /bin/sh
    command: -c "while true; do /app/scripts/ci/update-gha.sh; sleep 600; done"
    environment:
      KUBECONFIG: /etc/kubeconfigs/ci.yaml
      KUBE_SVC_ACCOUNT: isle-ci
      KUBE_NAMESPACE: islandora-metadata
      KUBE_CA_CERT_FILE: /run/secrets/KUBE_CA_CERT
      KUBE_SERVER_URL: ${KUBE_SERVER_URL}
    secrets:
      - KUBE_CA_CERT
    volumes:
      - ./:/app
      - /home/rollout/.docker:/root/.docker
      - /home/rollout/.env:/home/rollout/.env
      - /var/run/docker.sock:/var/run/docker.sock:z
      - ./conf/kubeconfigs:/etc/kubeconfigs:rw
secrets:
  KUBE_CA_CERT:
    file: ./certs/kube.base64.pem
