services:
  alpaca:
    environment:
      ALPACA_DERIVATIVE_FITS_URL: http://crayfits:8080
      ALPACA_DERIVATIVE_OCR_URL: http://hypercube:8080
      ALPACA_DERIVATIVE_HOMARUS_URL: http://homarus:8080
      ALPACA_DERIVATIVE_HOUDINI_URL: http://houdini:8080
      ALPACA_DERIVATIVE_LIBREOFFICE_URL: http://libreoffice:8080
      ALPACA_DERIVATIVE_WHISPER_URL: http://whisper:8080
      ALPACA_DERIVATIVE_OCRPDF_URL: http://ocrpdf:8080
      ALPACA_DERIVATIVE_HTR_URL: http://ocrpdf:8080
  drupal-cron:
    profiles: [none]
  rollout:
    profiles: [none]
  drupal-lehigh:
    profiles: [none]
  traefik:
    ports:
      - 8080:8080
  drupal:
    build:
      context: ./drupal
      x-bake:
        cache-from:
          - type=registry,ref=ghcr.io/lehigh-university-libraries/${COMPOSE_PROJECT_NAME}:local
          - type=registry,ref=ghcr.io/lehigh-university-libraries/${COMPOSE_PROJECT_NAME}:main
        cache-to:
          - type=inline
        platforms:
          - linux/arm64
    environment:
      URI_SCHEME: http
      DRUPAL_ENABLE_HTTPS: "false"
    secrets:
      - source: UID
    volumes:
      - drupal-public-files:/var/www/drupal/web/sites/default/files:rw
      - ./tmp/drupal-private-files:/var/www/drupal/private:rw
      - fcrepo-data:/fcrepo:rw
      - ./tmp/drupal:/tmp:rw
      - ./tmp/nginx:/var/lib/nginx/tmp:rw
      - ./tmp/nginx-cache:/var/cache/nginx:rw
      - ./drupal/rootfs/var/www/drupal:/var/www/drupal:z,rw,${CONSISTENCY}
  mariadb:
    ports:
      - 3306:3306
  memcached:
    command: memcached -m 256 -I 5m
  fits:
    image: islandora/fits:alpine-3-24@sha256:c4db834eb9c5847587febe2b19b68a679209dff4f89b6bad46e965ed96b6c319
    volumes:
      - ./tmp/fits:/tmp:rw
  crayfits:
    image: islandora/crayfits:alpine-3-24@sha256:d5c753d15fdb3d86cffdf539096f3b0770ed0d29afe548d1e0316ca10bce9cfd
    environment:
      JWKS_URI: https://${DOMAIN}/oauth/discovery/keys
    volumes:
      - ./tmp/crayfits:/tmp:rw
      - ./certs/rootCA.pem:/app/ca.pem:r
  hls:
    image: ghcr.io/lehigh-university-libraries/scyllaridae-hls:main@sha256:759c0447f398a6e2e0e53e94408793380aa0ba771fb24be224575e1b97320ffd
    environment:
      JWKS_URI: https://${DOMAIN}/oauth/discovery/keys
    secrets:
      - source: CERT_PUBLIC_KEY
      - source: CERT_AUTHORITY
      - source: JWT_PUBLIC_KEY
  homarus:
    image: islandora/homarus:alpine-3-24@sha256:26de05e35acdbd2c811403651ce607765ac56d348b238b728922b6c093c5c26c
    environment:
      JWKS_URI: https://${DOMAIN}/oauth/discovery/keys
    volumes:
      - ./tmp/homarus:/tmp:rw
      - ./certs/rootCA.pem:/app/ca.pem:r
  houdini:
    image: islandora/houdini:alpine-3-24@sha256:673f62abc452e34ea777a9d4ebecbd4be16615f2b8eccd8c2ce159b7aebbbfca
    environment:
      JWKS_URI: https://${DOMAIN}/oauth/discovery/keys
    volumes:
      - ./tmp/houdini:/tmp:rw
      - ./certs/rootCA.pem:/app/ca.pem:r
  hypercube:
    image: islandora/hypercube:alpine-3-24@sha256:f0dfb5f51a9e230efeedae53def8d644672390f00e05e70f4830a2ce4ff5cbf9
    environment:
      JWKS_URI: https://${DOMAIN}/oauth/discovery/keys
    volumes:
      - ./tmp/hypercube:/tmp:rw
      - ./certs/rootCA.pem:/app/ca.pem:r
  ocrpdf:
    image: ghcr.io/lehigh-university-libraries/scyllaridae-ocrpdf:main@sha256:5ace9ac69a6c8bf31f252bb8ed95a8600fc9be38a1990903f9cd348d0349a6cf
    environment:
      JWKS_URI: https://${DOMAIN}/oauth/discovery/keys
  libreoffice:
    image: ghcr.io/lehigh-university-libraries/scyllaridae-libreoffice:main@sha256:7855fd5f613e6c57dc0d1f1eafc2674e6c6811f31a600b8c7ec3c459a5faae38
    environment:
      JWKS_URI: https://${DOMAIN}/oauth/discovery/keys
    secrets:
      - source: CERT_PUBLIC_KEY
      - source: CERT_AUTHORITY
      - source: JWT_PUBLIC_KEY
  coverpage:
    image: ghcr.io/lehigh-university-libraries/scyllaridae-coverpage:main@sha256:006841e1c671391203ba9bd26541b7baf3f88cf390d3d853ee5dca360717f29f
    environment:
      JWKS_URI: https://${DOMAIN}/oauth/discovery/keys
    secrets:
      - source: CERT_PUBLIC_KEY
      - source: CERT_AUTHORITY
      - source: JWT_PUBLIC_KEY
  mergepdf:
    image: islandora/mergepdf:alpine-3-24@sha256:83c7c934d4dd9fa9a5412bfd64393d41b00d38cb530674b738bd53e8782c5a0d
    environment:
      JWKS_URI: https://${DOMAIN}/oauth/discovery/keys
      MAX_THREADS: 3
    secrets:
      - source: CERT_PUBLIC_KEY
      - source: CERT_AUTHORITY
      - source: JWT_PUBLIC_KEY
  drupal-static:
    volumes:
      - ./tmp/drupal-private-files/canonical/${DOMAIN}/0:/usr/share/nginx/drupal:ro
      - ./tmp/drupal-private-files/iiif/${DOMAIN}/294de3557d9d00b3d2d8a1e6aab028cf:/usr/share/nginx/iiif:ro
      - drupal-public-files:/var/www/drupal/web/sites/default/files:ro
      - ./tmp/drupal-static:/tmp:rw
      - ./tmp/nginx-static:/var/lib/nginx/tmp:rw
      - ./tmp/nginx-static-cache:/var/cache/nginx:rw
      - ./tmp/drupal/web:/var/www/drupal/web:rw
  fcrepo:
    volumes:
      - fcrepo-data:/data:rw
      - ./tmp/fcrepo:/tmp:rw
  triplet:
    volumes:
      - drupal-public-files:/public:r
      - ./tmp/drupal-private-files:/private:r
      - fcrepo-data:/fcrepo:r
      - ./certs/rootCA.pem:/etc/ssl/certs/lehigh.pem:r
      - ./conf/triplet/config.yaml:/etc/triplet/config.yaml:r
      - ./tmp/triplet-cache:/var/lib/triplet/cache:rw
