services:
  alpaca:
    environment:
      ALPACA_DERIVATIVE_FITS_URL: http://crayfits:8080
      ALPACA_DERIVATIVE_OCR_URL: http://hypercube:8080
      ALPACA_DERIVATIVE_HOMARUS_URL: http://homarus:8080
      ALPACA_DERIVATIVE_HOUDINI_URL: http://houdini:8080
      ALPACA_DERIVATIVE_LIBREOFFICE_URL: http://libreoffice:8080
      ALPACA_DERIVATIVE_WHISPER_URL: http://whisper:8080
      ALPACA_DERIVATIVE_OCRPDF_URL: http://ocrpdf:8080
      ALPACA_DERIVATIVE_HTR_URL: http://ocrpdf:8080
  drupal-cron:
    profiles: [none]
  rollout:
    profiles: [none]
  drupal-lehigh:
    profiles: [none]
  cantaloupe:
    volumes:
      - cantaloupe-data:/data:Z,rw
  drupal:
    build:
      context: ./drupal
      x-bake:
        cache-from:
          - type=registry,ref=ghcr.io/lehigh-university-libraries/${COMPOSE_PROJECT_NAME}:local
          - type=registry,ref=ghcr.io/lehigh-university-libraries/${COMPOSE_PROJECT_NAME}:main
        cache-to:
          - type=inline
        platforms:
          - linux/arm64
    environment:
      URI_SCHEME: http
      DRUPAL_ENABLE_HTTPS: "false"
    secrets:
      - source: UID
    volumes:
      - ./drupal/rootfs/var/www/drupal:/var/www/drupal:z,rw,${CONSISTENCY}
  mariadb:
    ports:
      - 3306:3306
  memcached:
    command: memcached -m 256 -I 5m
  fits:
    image: islandora/fits:6.3.12@sha256:2c17c6d571d443625d9ae475d983dc6ff7765ede80d95be37960ca5f4d0f156e
    volumes:
      - ./tmp/fits:/tmp:rw
  crayfits:
    image: islandora/crayfits:6.3.12@sha256:0c58e818ee175f5fed0a9c212555f893e6f5dae60cccd241d016ceebc9ba1296
    environment:
      JWKS_URI: https://${DOMAIN}/oauth/discovery/keys
    volumes:
      - ./tmp/crayfits:/tmp:rw
      - ./certs/rootCA.pem:/app/ca.pem:r
  hls:
    image: ghcr.io/lehigh-university-libraries/scyllaridae-hls:main@sha256:532cfdb944e837c33a56c53e61b1a8ab4f761a30ec43e283e21e725526a17275
    environment:
      JWKS_URI: https://${DOMAIN}/oauth/discovery/keys
    secrets:
      - source: CERT_PUBLIC_KEY
      - source: CERT_AUTHORITY
      - source: JWT_PUBLIC_KEY
  homarus:
    image: islandora/homarus:6.3.12@sha256:5864497199d001a83d17810991261ee37116b711d14a6a9eeafc0fd75399c0b0
    environment:
      JWKS_URI: https://${DOMAIN}/oauth/discovery/keys
    volumes:
      - ./tmp/homarus:/tmp:rw
      - ./certs/rootCA.pem:/app/ca.pem:r
  houdini:
    image: islandora/houdini:6.3.12@sha256:55d066cf9277f6d8a273f14d2ea405a5c0186db069d357926f14854120507e5f
    environment:
      JWKS_URI: https://${DOMAIN}/oauth/discovery/keys
    volumes:
      - ./tmp/houdini:/tmp:rw
      - ./certs/rootCA.pem:/app/ca.pem:r
  hypercube:
    image: islandora/hypercube:6.3.12@sha256:89019b849bc0c1114c86ca8eb7ee568722e548c777048aabd04474f41ddfc0b6
    environment:
      JWKS_URI: https://${DOMAIN}/oauth/discovery/keys
    volumes:
      - ./tmp/hypercube:/tmp:rw
      - ./certs/rootCA.pem:/app/ca.pem:r
  ocrpdf:
    image: ghcr.io/lehigh-university-libraries/scyllaridae-ocrpdf:main@sha256:3ae2d68ef4eb5d351d7da9d052a0ad1d5b76ec69a34675e1888a01c758d3c97f
    environment:
      JWKS_URI: https://${DOMAIN}/oauth/discovery/keys
  libreoffice:
    image: ghcr.io/lehigh-university-libraries/scyllaridae-libreoffice:main@sha256:3c769b1fc091a153290c85ec6954c07caca595e61bbf0bef3b4a75c2bbe6f629
    environment:
      JWKS_URI: https://${DOMAIN}/oauth/discovery/keys
    secrets:
      - source: CERT_PUBLIC_KEY
      - source: CERT_AUTHORITY
      - source: JWT_PUBLIC_KEY
  coverpage:
    image: ghcr.io/lehigh-university-libraries/scyllaridae-coverpage:main@sha256:d4525a8aec217026f25ea570854268ef92f7ff0a6b073e3aadf60fac5a2b16e2
    environment:
      JWKS_URI: https://${DOMAIN}/oauth/discovery/keys
    secrets:
      - source: CERT_PUBLIC_KEY
      - source: CERT_AUTHORITY
      - source: JWT_PUBLIC_KEY
  mergepdf:
    image: islandora/mergepdf:6.3.12@sha256:cddc20427e0e8c1ed83cfecbddcc43b89ed4e79baa1d7d583c3a6eb113e93aa6
    environment:
      JWKS_URI: https://${DOMAIN}/oauth/discovery/keys
      MAX_THREADS: 3
    secrets:
      - source: CERT_PUBLIC_KEY
      - source: CERT_AUTHORITY
      - source: JWT_PUBLIC_KEY
