services:
  alpaca:
    environment:
      ALPACA_MAX_REDELIVERIES: 1
      ALPACA_DERIVATIVE_HOUDINI_CONSUMERS: 3
      ALPACA_DERIVATIVE_HOUDINI_URL: http://houdini:8080
      ALPACA_DERIVATIVE_LIBREOFFICE_URL: http://libreoffice:8080
      ALPACA_DERIVATIVE_MERGEPDF_URL: http://mergepdf:8080
      ALPACA_DERIVATIVE_COVERPAGE_URL: http://coverpage:8080
  coverpage:
    image: ghcr.io/lehigh-university-libraries/scyllaridae-coverpage:main@sha256:3773d3da4cacc5082fd817d746af24db199f6e3524e4c0103dc20ad4576a2023
    environment:
      JWKS_URI: https://${DOMAIN}/oauth/discovery/keys
    volumes:
      - ./certs/rootCA.pem:/app/ca.pem:r
  mergepdf:
    image: islandora/mergepdf:6.4.2@sha256:b59a5e1cda8b83d99dfa4578dd7fc3c3fc1be4fe51cdca38d6f26e6a36921dec
    environment:
      JWKS_URI: https://${DOMAIN}/oauth/discovery/keys
      MAX_THREADS: 3
    secrets:
      - source: CERT_PUBLIC_KEY
      - source: CERT_AUTHORITY
      - source: JWT_PUBLIC_KEY
  libreoffice:
    image: ghcr.io/lehigh-university-libraries/scyllaridae-libreoffice:main@sha256:7f2db102e678eba6e3d6967c65e42cf0ec0bf1c4df09f547ea6e99b81ae6c289
    environment:
      JWKS_URI: https://${DOMAIN}/oauth/discovery/keys
    secrets:
      - source: CERT_PUBLIC_KEY
      - source: CERT_AUTHORITY
      - source: JWT_PUBLIC_KEY
  houdini:
    image: islandora/houdini:6.4.2@sha256:f683efe91aaba75de106aa843634a6a665c467a033f6c7d1de22957d8286f608
    environment:
      JWKS_URI: https://${DOMAIN}/oauth/discovery/keys
    secrets:
      - source: CERT_PUBLIC_KEY
      - source: CERT_AUTHORITY
      - source: JWT_PUBLIC_KEY
    volumes:
      - ./tmp/houdini:/tmp:rw
  github-actions-runner:
    image: ghcr.io/lehigh-university-libraries/actions-runner:main
    environment:
      GITHUB_RUNNER_TOKEN: ${GITHUB_RUNNER_TOKEN}
      GITHUB_REPO: "https://github.com/lehigh-university-libraries/isle-preserve"
      LABELS: isle
      KUBECONFIG: /etc/kubeconfigs/ci.yaml
    volumes:
      - actions-runner-data:/app:rw
      - /var/run/docker.sock:/var/run/docker.sock:z
      - ./conf/kubeconfigs:/etc/kubeconfigs:r
  gha-runner-updater:
    image: ghcr.io/lehigh-university-libraries/actions-runner:main
    working_dir: /app
    entrypoint: /bin/sh
    command: -c "while true; do /app/scripts/ci/update-gha.sh; sleep 600; done"
    environment:
      KUBECONFIG: /etc/kubeconfigs/ci.yaml
      KUBE_SVC_ACCOUNT: isle-ci
      KUBE_NAMESPACE: islandora-metadata
      KUBE_CA_CERT_FILE: /run/secrets/KUBE_CA_CERT
      KUBE_SERVER_URL: ${KUBE_SERVER_URL}
    secrets:
      - KUBE_CA_CERT
    volumes:
      - ./:/app
      - /home/rollout/.docker:/root/.docker
      - /home/rollout/.env:/home/rollout/.env
      - /var/run/docker.sock:/var/run/docker.sock:z
      - ./conf/kubeconfigs:/etc/kubeconfigs:rw
secrets:
  KUBE_CA_CERT:
    file: ./certs/kube.base64.pem
