---
apiVersion: v1
kind: Service
metadata:
  name: islandora-cache-warmer
spec:
  selector:
    app: islandora-cache-warmer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: islandora-cache-warmer
spec:
  replicas: 3
  selector:
    matchLabels:
      app: islandora-cache-warmer
  template:
    metadata:
      labels:
        app: islandora-cache-warmer
    spec:
      containers:
        - name: scyllaridae-cache-warmer
          image: lehighlts/scyllaridae-cache-warmer:main@sha256:908aee7dbf2db4ec186cd7712f0aa765cd9cbe522c713441cba19f9d1a4530e4
          imagePullPolicy: IfNotPresent
          env:
            - name: "DRUPAL_URL"
              value: "https://preserve.lehigh.edu"
            - name: "SKIP_JWT_VERIFY"
              value: "true"
          resources:
            requests:
              memory: "32Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
          ports:
            - containerPort: 8080
              hostPort: 8080
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
