---
apiVersion: v1
kind: Service
metadata:
  name: islandora-cache-warmer
spec:
  selector:
    app: islandora-cache-warmer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: islandora-cache-warmer
spec:
  replicas: 3
  selector:
    matchLabels:
      app: islandora-cache-warmer
  template:
    metadata:
      labels:
        app: islandora-cache-warmer
    spec:
      containers:
        - name: scyllaridae-cache-warmer
          image: lehighlts/scyllaridae-cache-warmer:main@sha256:12e8e31ddbc82afa4ea8a631cf27aab109ede15c92e5286a08909b30e4f5d2fb
          imagePullPolicy: IfNotPresent
          env:
            - name: "DRUPAL_URL"
              value: "https://preserve.lehigh.edu"
            - name: "JWKS_URI"
              value: "https://preserve.lehigh.edu/oauth/discovery/keys"
          resources:
            requests:
              memory: "32Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
          ports:
            - containerPort: 8080
              hostPort: 8080
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
