---
apiVersion: v1
kind: Service
metadata:
  name: islandora-crayfits
spec:
  selector:
    app: islandora-crayfits
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: islandora-crayfits
spec:
  replicas: 3
  selector:
    matchLabels:
      app: islandora-crayfits
  template:
    metadata:
      labels:
        app: islandora-crayfits
    spec:
      containers:
        - name: scyllaridae-crayfits
          image: islandora/crayfits:7.0.12@sha256:c5546155f2b1b9f60f60aca282694480a938bd437605096938e86631bcbb3f80
          imagePullPolicy: IfNotPresent
          env:
            - name: "JWKS_URI"
              value: "https://preserve.lehigh.edu/oauth/discovery/keys"
            - name: "CRAYFITS_WEBSERVICE_URI"
              value: "http://fits:8080/fits/examine"
            - name: CERT_PUBLIC_KEY
              valueFrom:
                configMapKeyRef:
                  name: islandora-prod-ca
                  key: islandora-prod.pem
          resources:
            requests:
              memory: "12Gi"
              cpu: "100m"
            limits:
              memory: "12Gi"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
