---
apiVersion: v1
kind: Service
metadata:
  name: islandora-imagemagick
spec:
  selector:
    app: islandora-imagemagick
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: islandora-imagemagick
spec:
  replicas: 12
  selector:
    matchLabels:
      app: islandora-imagemagick
  template:
    metadata:
      labels:
        app: islandora-imagemagick
    spec:
      containers:
        - name: scyllaridae-imagemagick
          image: islandora/houdini:houdini-vips@sha256:c40f144e19be723e2ffd734011663405d360425db74c21732e5bf631ffb0c1c1
          imagePullPolicy: IfNotPresent
          env:
            - name: "JWKS_URI"
              value: "https://preserve.lehigh.edu/oauth/discovery/keys"
            - name: CERT_PUBLIC_KEY
              valueFrom:
                configMapKeyRef:
                  name: islandora-prod-ca
                  key: islandora-prod.pem
          resources:
            requests:
              memory: "8Gi"
              cpu: "100m"
            limits:
              memory: "8Gi"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
