---
apiVersion: v1
kind: Service
metadata:
  name: islandora-mergepdf
spec:
  selector:
    app: islandora-mergepdf
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: islandora-mergepdf
spec:
  replicas: 3
  selector:
    matchLabels:
      app: islandora-mergepdf
  template:
    metadata:
      labels:
        app: islandora-mergepdf
    spec:
      containers:
        - name: scyllaridae-mergepdf
          image: islandora/mergepdf:6.4.0@sha256:a335404ec4b39c987e85719c454c7eb45103f82e3008001d01e0920c09434365
          imagePullPolicy: IfNotPresent
          env:
            - name: MAX_WIDTH
              value: "1200"
            - name: MAX_THREADS
              value: "7"
            - name: "JWKS_URI"
              value: "https://preserve.lehigh.edu/oauth/discovery/keys"
            - name: CERT_PUBLIC_KEY
              valueFrom:
                configMapKeyRef:
                  name: islandora-prod-ca
                  key: islandora-prod.pem
          resources:
            requests:
              memory: "24Gi"
              cpu: "500m"
            limits:
              memory: "24Gi"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
