---
apiVersion: v1
kind: Service
metadata:
  name: sentence-transformer
spec:
  selector:
    app: sentence-transformer
  ports:
    - protocol: TCP
      port: 8094
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentence-transformer
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sentence-transformer
  template:
    metadata:
      labels:
        app: sentence-transformer
    spec:
      containers:
        - name: sentence-transformer
          image: ghcr.io/lehigh-university-libraries/sentence-transformer:main@sha256:40d05bbce282d29eeaa99b5d4766621d3df74b7ab6a86e81c4ade36ff36c772c
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "2Gi"
              cpu: "1000m"
            limits:
              memory: "2Gi"
          ports:
            - containerPort: 8080
              hostPort: 8094
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 30
