---
apiVersion: v1
kind: Service
metadata:
  name: islandora-whisper
spec:
  selector:
    app: islandora-whisper
  ports:
    - protocol: TCP
      targetPort: 8080
      port: 8093
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: islandora-whisper
spec:
  replicas: 3
  selector:
    matchLabels:
      app: islandora-whisper
  template:
    metadata:
      labels:
        app: islandora-whisper
    spec:
      containers:
        - name: scyllaridae-whisper
          image: lehighlts/scyllaridae-whisper:main@sha256:085643cfbe11bbfc79ae3bd1c4764fa3d3835694325df38a04054651e7b7d62b
          imagePullPolicy: IfNotPresent
          env:
            - name: "JWKS_URI"
              value: "https://preserve.lehigh.edu/oauth/discovery/keys"
          resources:
            requests:
              memory: "2Gi"
              cpu: "500m"
            limits:
              memory: "10Gi"
          ports:
            - containerPort: 8080
              hostPort: 8093
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
