---
apiVersion: v1
kind: Service
metadata:
  name: islandora-whisper
spec:
  selector:
    app: islandora-whisper
  ports:
    - protocol: TCP
      targetPort: 8080
      port: 8888
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: islandora-whisper
spec:
  replicas: 3
  selector:
    matchLabels:
      app: islandora-whisper
  template:
    metadata:
      labels:
        app: islandora-whisper
    spec:
      volumes:
        - name: islandora-prod-ca
          configMap:
            name: islandora-prod-ca
            items:
              - key: islandora-prod.pem
                path: ca.pem
      containers:
        - name: scyllaridae-whisper
          image: ghcr.io/lehigh-university-libraries/scyllaridae-whisper:main@sha256:213f2559d1df33554d549195f81d7f28c3f93e110992ce00f2f5be562b920764
          imagePullPolicy: IfNotPresent
          env:
            - name: "JWKS_URI"
              value: "https://preserve.lehigh.edu/oauth/discovery/keys"
          resources:
            requests:
              memory: "32Gi"
              cpu: "500m"
            limits:
              memory: "32Gi"
          ports:
            - containerPort: 8080
              hostPort: 8888
          volumeMounts:
            - name: islandora-prod-ca
              mountPath: /app/ca.pem
              subPath: ca.pem
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
