---
apiVersion: v1
kind: Service
metadata:
  name: islandora-whisper
spec:
  selector:
    app: islandora-whisper
  ports:
    - protocol: TCP
      targetPort: 8080
      port: 8888
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: islandora-whisper
spec:
  replicas: 3
  selector:
    matchLabels:
      app: islandora-whisper
  template:
    metadata:
      labels:
        app: islandora-whisper
    spec:
      volumes:
        - name: islandora-prod-ca
          configMap:
            name: islandora-prod-ca
            items:
              - key: islandora-prod.pem
                path: ca.pem
      containers:
        - name: scyllaridae-whisper
          image: lehighlts/scyllaridae-whisper:main@sha256:e38b3a04008399475d94d68c841c7efe8a1ad9eae4c04727df5b7310a2d3dc1c
          imagePullPolicy: IfNotPresent
          env:
            - name: "JWKS_URI"
              value: "https://preserve.lehigh.edu/oauth/discovery/keys"
            - name: "WHISPER_PROCESSORS"
              value: "2"
            - name: "WHISPER_THREADS"
              value: "8"
          resources:
            requests:
              memory: "32Gi"
              cpu: "500m"
            limits:
              memory: "32Gi"
              nvidia.com/gpu: 4
          ports:
            - containerPort: 8080
              hostPort: 8888
          volumeMounts:
            - name: islandora-prod-ca
              mountPath: /app/ca.pem
              subPath: ca.pem
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
