<?php

/**
 * @file
 * Primary module hooks for Views Attachment Tab module.
 */

use Drupal\Component\Utility\Html;
use Drupal\views\ViewExecutable;

/**
 * Implements hook_views_pre_render().
 */
function views_attachment_tabs_views_pre_render(ViewExecutable $view) {

  // Get the current display.
  $display = $view->getDisplay();

  // And get the list of extenders for this display.
  $extenders = $display->getExtenders();

  // If the id of our plugin is not in the list something is wrong.
  if (!isset($extenders['attachment_tabs'])) {
    return $view;
  }

  // Manage attachment tab group parent
  // Checks if attachment tab option is enabled and that attachments exist.
  $child_attachments = array_merge($view->attachment_before, $view->attachment_after);

  // Ensure that the attachment tab group has child attachments.
  if ($extenders['attachment_tabs']->options['attachment_tabs_enabled'] && count($child_attachments) > 0) {
    // Parent view is being rendered so has a BigPipe DOM ID.
    // Child attachments may not have DOM IDs yet, but we can
    // make the parent DOM id available to the attachment and via JS.
    $parent_dom_id = "vat-parent-" . $view->dom_id;
    $tabs = [];

    $default_attachment_display = array_key_exists('default_attachment_display', $view->style_plugin->options) ? $view->style_plugin->options['default_attachment_display'] : '';
    $display->setOption('css_class', "view-attachment-tab-parent {$view->current_display} {$parent_dom_id}");

    foreach ($child_attachments as $attachment) {
      /**  @var \Drupal\views\ViewExecutable $attached_view */
      $attached_view = $attachment['#view'];
      $attached_display = $attached_view->getDisplay();
      $id = $attached_view->current_display;
      $attached_display->setOption('attachment_tab', TRUE);
      $attached_display->setOption('parent_dom', $parent_dom_id);

      $css_classes = "view-attachment-tab view-attachment-tab-{$attached_view->current_display} {$attached_view->current_display}";

      if ($id != $default_attachment_display) {
        $css_classes .= " view-attachment-tab-hidden";
      }

      $attached_display->setOption('css_class', $css_classes);

      $tabs[$id] = [
        'label' => $attached_view->getTitle(),
        'id' => $id,
        'parent_dom_id' => $parent_dom_id,
        'target' => '.view-attachment-tab-' . str_replace('_', '-', $id),
        'default' => $id == $default_attachment_display ? TRUE : FALSE,
      ];
    }

    $tab_interface = [
      '#theme' => 'views_attachment_tabs',
      '#tabs' => $tabs,
      '#weight' => -1,
    ];

    $display->setOption('attachment_tab_ui', $tab_interface);

    $view->element['#attached']['drupalSettings']['viewsAttachmentTabs'] = [
      'tabGroup' => [
        'views_dom_id:' . $view->dom_id => [
          'view_name' => $view->storage->id(),
          'view_display_id' => $view->current_display,
          'view_args' => Html::escape(implode('/', $view->args)),
          'view_path' => Html::escape(\Drupal::service('path.current')
            ->getPath()),
          'view_base_path' => $view->getPath(),
          'view_dom_id' => $view->dom_id,
          'view_child_attachments' => count($child_attachments),
          'view_tabs' => $tabs,
        ],
      ],
    ];
    $view->element['#attached']['library'][] = 'views_attachment_tabs/views_attachment_tabs.main';
  }
  // Manages tab group child attachments.
  return $view;

}

/**
 * Implements hook_preprocess_views_view().
 */
function views_attachment_tabs_preprocess_views_view(&$vars) {
  /** @var \Drupal\views\ViewExecutable $view */
  $view = &$vars["view"];
  $display = $view->getDisplay();
  $tab_ui = $display->getOption('attachment_tab_ui');

  if ($tab_ui) {
    $vars['header']['attachment_tab_build'] = $tab_ui;
  }
}

/**
 * Implements hook_theme().
 */
function views_attachment_tabs_theme($existing, $type, $theme, $path) {
  return [
    'views_attachment_tabs' => [
      'template' => 'views/views_attachment_tabs',
      'variables' => [
        'tabs' => [],
      ],
    ],
  ];
}
