apiVersion: v1
kind: ServiceAccount
metadata:
  name: isle-ci
  namespace: islandora-metadata
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: isle-ci-role
  namespace: islandora-metadata
rules:
  - apiGroups: ["", "apps"]
    resources: ["deployments", "services"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: isle-ci-binding
  namespace: islandora-metadata
subjects:
  - kind: ServiceAccount
    name: isle-ci
    namespace: islandora-metadata
roleRef:
  kind: Role
  name: isle-ci-role
  apiGroup: rbac.authorization.k8s.io
