name: deploy-prod
on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  deploy-prod:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - run: ./scripts/ci/trigger-rollout.sh
        env:
          ROLLOUT_URL: https://islandora-prod.lib.lehigh.edu/_rollout
