name: lint-test-build-push
on:
  workflow_dispatch:
  push:
    branches:
      - "**"
    paths-ignore:
      - "ci/**/*.yaml"
      - "**/*.md"
      - "renovate.json5"

concurrency:
  group: "one-job-at-a-time"
  cancel-in-progress: false

permissions:
  contents: read
  id-token: write

jobs:
  lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - uses: hadolint/hadolint-action@2332a7b74a6de0dda2e2221d575162eba76ba5e5 # v3.3.0
        with:
          dockerfile: ./drupal/Dockerfile
          verbose: true

      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: 24

      - name: Setup PHP
        uses: shivammathur/setup-php@7c071dfe9dc99bdf297fa79cb49ea005b9fcadbc # v2
        with:
          php-version: 8.3
          tools: composer:v2

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
        working-directory: codebase

      - name: Cache dependencies
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - run: composer install
        working-directory: codebase

      - run: ./codebase/scripts/test-mirador-js.sh

      - run: ./scripts/ci/lint.sh

  build-push:
    needs:
      - lint
    name: "docker build+push"
    uses: lehigh-university-libraries/gha/.github/workflows/build-push-ghcr.yaml@e26d86abfbe300be4d93570b666651c11471995b # main
    with:
      context: drupal
    permissions:
      contents: read
      packages: write
    secrets: inherit

  deploy-test:
    needs:
      - lint
      - build-push
    uses: ./.github/workflows/deploy.yaml
    with:
      url: https://wight.cc.lehigh.edu/_rollout

  test:
    runs-on: [self-hosted, isle]
    needs: [deploy-test]
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - run: ./scripts/ci/test.sh
        env:
          DOMAIN: wight.cc.lehigh.edu

      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: 24

      - run: ./scripts/ci/playwright.sh
        env:
          DOMAIN: wight.cc.lehigh.edu

      - if: ${{ always() }}
        run: ./scripts/ci/cleanup.sh

  deploy-stage:
    if: github.ref == 'refs/heads/main'
    needs: [test]
    uses: ./.github/workflows/deploy.yaml
    with:
      url: https://islandora-test.lib.lehigh.edu/_rollout
